name: mirra
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.15.8
  flutter_spinkit: ^5.2.1
  google_fonts: 6.1.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  image_picker: ^1.0.8
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  flutter_firebase_recaptcha: ^1.0.2
  intro_slider: ^4.2.1
  simple_animations: ^5.0.2
  flutter_fadein: ^2.0.0
  font_awesome_flutter: ^10.7.0
  confetti: ^0.7.0
  swipe_cards: ^2.0.0+1
  http: ^1.2.0
  firebase_storage: ^11.6.9
  firebase_storage_mocks: ^0.6.1
  firebase_storage_web: ^3.7.3
  firebase_core_web: ^2.11.5
  firebase_rules: ^0.2.0
  location: ^6.0.2
  geocoding: ^3.0.0
  qr_flutter: ^4.1.0
  pretty_qr_code: ^3.3.0
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.5.3
  google_maps_place_picker_mb: ^3.1.2
  flutter_card_swiper: ^7.0.1
  cloud_functions: ^4.6.8
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.7.19
  flutter_typeahead: ^5.2.0
  flutter_multiselect: ^1.0.0
  geolocator: ^10.1.1
  dots_indicator: ^3.0.0
  flutter_bloc: ^8.1.5
  permission_handler: ^11.3.1
  fl_chart: ^0.67.0
  in_app_purchase: ^3.2.0
  vibration: ^1.8.4
  url_launcher: ^6.2.6
  google_mobile_ads: ^5.0.0
  skeleton_loader: ^2.0.0+4
  cached_network_image: ^3.3.1
  webview_flutter: ^4.7.0
  uuid: ^4.4.0
  google_sign_in: ^6.2.1
  curved_navigation_bar: ^1.0.3
  purchases_flutter: ^6.29.0
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/images/Asset_6.png
    - assets/images/Asset_3@10x.png
    - assets/pdfs/
    - assets/fonts/
    - assets/audios/
    - assets/videos/
    - assets/rive_animations/
    - assets/lottie_animations/
    - assets/images/UI_avatar@2x.png

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Thin.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
