///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsImagesAsset310x = 'assets/images/Asset_3@10x.png';
  static const String assetsImagesAsset6 = 'assets/images/Asset_6.png';
  static const String assetsImagesUIAvatar2x = 'assets/images/UI_avatar@2x.png';
  static const String assetsMirrorAppIcon = 'assets/mirror_app_icon.png';
  static const String audiosFavicon = 'assets/audios/favicon.png';
  static const String bebasNeueBebasNeueRegular =
      'assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf';
  static const String bebasNeueOFL = 'assets/fonts/Bebas_Neue/OFL.txt';
  static const String fontsFavicon = 'assets/fonts/favicon.png';
  static const String images153DD5DB35C242F39EE215B4D2306DF0 =
      'assets/images/153DD5DB-35C2-42F3-9EE2-15B4D2306DF0.png';
  static const String images325B67732ABC42FD9043836D715E327C =
      'assets/images/325B6773-2ABC-42FD-9043-836D715E327C.png';
  static const String imagesA6409C4E2A39415C84F12C5657AA50DC =
      'assets/images/A6409C4E-2A39-415C-84F1-2C5657AA50DC.png';
  static const String imagesAppLauncherIcon =
      'assets/images/app_launcher_icon.png';
  static const String imagesAsset10 = 'assets/images/Asset_10.svg';
  static const String imagesAsset11 = 'assets/images/Asset_11.png';
  static const String imagesAsset310x = 'assets/images/Asset_3@10x.png';
  static const String imagesAsset6 = 'assets/images/Asset_6.png';
  static const String imagesAsset610x = 'assets/images/Asset_6@10x.png';
  static const String imagesCardHeader2x = 'assets/images/card_header@2x.png';
  static const String imagesD51136ED043D4C43B78B2401B36407E9 =
      'assets/images/D51136ED-043D-4C43-B78B-2401B36407E9.png';
  static const String imagesFavicon = 'assets/images/favicon.png';
  static const String imagesMessagesEmpty2x =
      'assets/images/messagesEmpty@2x.png';
  static const String imagesMirraloadingWhite =
      'assets/images/mirraloading_White.gif';
  static const String imagesONExpenses3x = 'assets/images/ON_expenses@3x.png';
  static const String imagesONExplore3x = 'assets/images/ON_explore@3x.png';
  static const String imagesONMessages3x = 'assets/images/ON_messages@3x.png';
  static const String imagesPngtreeNeonCircleFrameDesignPngImage4524951 =
      'assets/images/pngtree-neon-circle-frame-design-png-image_4524951.jpeg';
  static const String imagesUIAvatar2x = 'assets/images/UI_avatar@2x.png';
  static const String latoLatoBlack = 'assets/fonts/Lato/Lato-Black.ttf';
  static const String latoLatoBlackItalic =
      'assets/fonts/Lato/Lato-BlackItalic.ttf';
  static const String latoLatoBold = 'assets/fonts/Lato/Lato-Bold.ttf';
  static const String latoLatoBoldItalic =
      'assets/fonts/Lato/Lato-BoldItalic.ttf';
  static const String latoLatoItalic = 'assets/fonts/Lato/Lato-Italic.ttf';
  static const String latoLatoLight = 'assets/fonts/Lato/Lato-Light.ttf';
  static const String latoLatoLightItalic =
      'assets/fonts/Lato/Lato-LightItalic.ttf';
  static const String latoLatoRegular = 'assets/fonts/Lato/Lato-Regular.ttf';
  static const String latoLatoThin = 'assets/fonts/Lato/Lato-Thin.ttf';
  static const String latoLatoThinItalic =
      'assets/fonts/Lato/Lato-ThinItalic.ttf';
  static const String latoOFL = 'assets/fonts/Lato/OFL.txt';
  static const String lottieAnimationsFavicon =
      'assets/lottie_animations/favicon.png';
  static const String pdfsFavicon = 'assets/pdfs/favicon.png';
  static const String riveAnimationsFavicon =
      'assets/rive_animations/favicon.png';
  static const String videosFavicon = 'assets/videos/favicon.png';
}
