// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdke-u286vWvSQ9C7ETs0SClVUPUULMcA',
    appId: '1:928648526048:web:2bf751d2ad6b7bb9a8b885',
    messagingSenderId: '928648526048',
    projectId: 'mirr00',
    authDomain: 'mirr00.firebaseapp.com',
    databaseURL:
        'https://mirr00-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mirr00.appspot.com',
    measurementId: 'G-T6ZE98GE4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0lXhMF3jdfNUNAFEcAl2fDHEMba7Kxzo',
    appId: '1:928648526048:android:733a6c4691c28e99a8b885',
    messagingSenderId: '928648526048',
    projectId: 'mirr00',
    databaseURL:
        'https://mirr00-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mirr00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA005LXhMze_RHEXwm948DLZAmmzGZESF4',
    appId: '1:928648526048:ios:fb3a88b90f7baf32a8b885',
    messagingSenderId: '928648526048',
    projectId: 'mirr00',
    databaseURL:
        'https://mirr00-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mirr00.appspot.com',
    androidClientId:
        '928648526048-v806mtb5enc0t3fqn1johts8i0u5cuae.apps.googleusercontent.com',
    iosClientId:
        '928648526048-5iloosu4hu08v64p2drgvsiided9r6f4.apps.googleusercontent.com',
    iosBundleId: 'com.themirrorsocial.mirra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA005LXhMze_RHEXwm948DLZAmmzGZESF4',
    appId: '1:928648526048:ios:520fab085448c59ba8b885',
    messagingSenderId: '928648526048',
    projectId: 'mirr00',
    databaseURL:
        'https://mirr00-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mirr00.appspot.com',
    androidClientId:
        '928648526048-v806mtb5enc0t3fqn1johts8i0u5cuae.apps.googleusercontent.com',
    iosClientId:
        '928648526048-ofqbv9oq5s9tgqsglt9knjl8ke7b7p8i.apps.googleusercontent.com',
    iosBundleId: 'com.themirrorsocial.mirra.RunnerTests',
  );
}
