// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdke-u286vWvSQ9C7ETs0SClVUPUULMcA',
    appId: '1:928648526048:web:2bf751d2ad6b7bb9a8b885',
    messagingSenderId: '928648526048',
    projectId: 'mirr00',
    authDomain: 'mirr00.firebaseapp.com',
    storageBucket: 'mirr00.appspot.com',
    measurementId: 'G-T6ZE98GE4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0lXhMF3jdfNUNAFEcAl2fDHEMba7Kxzo',
    appId: '1:928648526048:android:c6f67898f6218c76a8b885',
    messagingSenderId: '928648526048',
    projectId: 'mirr00',
    storageBucket: 'mirr00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA005LXhMze_RHEXwm948DLZAmmzGZESF4',
    appId: '1:928648526048:ios:cced27f8edebb9f5a8b885',
    messagingSenderId: '928648526048',
    projectId: 'mirr00',
    storageBucket: 'mirr00.appspot.com',
    iosClientId:
        '928648526048-62egttvilccpnbobv82t1lct5e7loo8l.apps.googleusercontent.com',
    iosBundleId: 'com.themirrorsocial.theMirrorSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA005LXhMze_RHEXwm948DLZAmmzGZESF4',
    appId: '1:928648526048:ios:ea533a0fd168dba7a8b885',
    messagingSenderId: '928648526048',
    projectId: 'mirr00',
    storageBucket: 'mirr00.appspot.com',
    iosClientId:
        '928648526048-gobi24h7te3llro1a50vhg8o7i5737o5.apps.googleusercontent.com',
    iosBundleId: 'com.themirrorsocial.theMirrorSocial.RunnerTests',
  );
}
